<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Lesson;
use App\Models\Exercise;
use App\Models\ExerciseItem;

class A1_Exercises_Fixer extends Seeder
{
    public function run(): void
    {
        $data = [
            'Möchten: Almanca Modal Fiiller' => [
                ['Ich möchte einen Kaffee, bitte.','Bir kahve istiyorum, lütfen.'],
                ['Was möchten Sie trinken?','Ne içmek istiyorsunuz?'],
                ['Er möchte nach Berlin fahren.','O Berlin\'e gitmek istiyor.'],
                ['Wir möchten einen Tisch reservieren.','Bir masa ayırtmak istiyoruz.'],
                ['Möchtest du etwas essen?','Bir şeyler yemek ister misin?'],
                ['Sie möchte Ärztin werden.','O doktor olmak istiyor.'],
                ['Ich möchte bitte die Rechnung.','Hesabı istiyorum lütfen.'],
                ['Möchten Sie noch etwas?','Başka bir şey ister misiniz?'],
                ['Das Kind möchte Schokolade haben.','Çocuk çikolata istiyor.'],
                ['Wir möchten im Restaurant essen.','Restoranda yemek yemek istiyoruz.'],
                ['Ich möchte kein Fleisch essen.','Et yemek istemiyorum.'],
                ['Was möchtest du zum Geburtstag?','Doğum günün için ne istiyorsun?'],
                ['Er möchte nicht warten.','O beklemek istemiyor.'],
                ['Möchtest du Kaffee oder Tee?','Kahve mi yoksa çay mı istersin?'],
                ['Wir möchten das Museum besuchen.','Müzeyi ziyaret etmek istiyoruz.'],
                ['Sie möchten bitte leiser sprechen.','Lütfen daha sessiz konuşmak istersiniz.'],
                ['Ich möchte eine Fahrkarte kaufen.','Bir bilet satın almak istiyorum.'],
                ['Möchten Sie in einem Einzelzimmer übernachten?','Tek kişilik odada kalmak ister misiniz?'],
                ['Er möchte Deutsch lernen.','O Almanca öğrenmek istiyor.'],
                ['Wir möchten uns bedanken.','Teşekkür etmek istiyoruz.'],
            ],
            'Wollen: Almanca Modal Fiiller' => [
                ['Ich will heute früh aufstehen.','Bugün erken kalkmak istiyorum.'],
                ['Willst du mitkommen?','Birlikte gelmek ister misin?'],
                ['Er will ein neues Auto kaufen.','O yeni bir araba satın almak istiyor.'],
                ['Was wollen Sie hier machen?','Burada ne yapmak istiyorsunuz?'],
                ['Wir wollen nach Spanien reisen.','İspanya\'ya seyahat etmek istiyoruz.'],
                ['Sie will Englisch lernen.','O İngilizce öğrenmek istiyor.'],
                ['Die Kinder wollen draußen spielen.','Çocuklar dışarıda oynamak istiyor.'],
                ['Ich will nicht mehr warten.','Artık beklemek istemiyorum.'],
                ['Wollt ihr ins Kino gehen?','Sinemaya gitmek ister misiniz?'],
                ['Er will Arzt werden.','O doktor olmak istiyor.'],
                ['Ich will heute Abend kochen.','Bu akşam yemek pişirmek istiyorum.'],
                ['Sie wollen ein Haus bauen.','Onlar bir ev inşa etmek istiyor.'],
                ['Willst du mir helfen?','Bana yardım etmek ister misin?'],
                ['Wir wollen mehr Sport machen.','Daha fazla spor yapmak istiyoruz.'],
                ['Was will er beruflich machen?','O mesleki olarak ne yapmak istiyor?'],
                ['Ich will heute nicht ausgehen.','Bugün dışarı çıkmak istemiyorum.'],
                ['Wollt ihr das Spiel sehen?','Maçı izlemek ister misiniz?'],
                ['Sie will ihren Eltern besuchen.','O ebeveynlerini ziyaret etmek istiyor.'],
                ['Wir wollen zusammen essen.','Birlikte yemek yemek istiyoruz.'],
                ['Er will unbedingt Erfolg haben.','O mutlaka başarılı olmak istiyor.'],
            ],
            'Dürfen: Almanca Modal Fiiller' => [
                ['Darf ich hier sitzen?','Buraya oturabilir miyim?'],
                ['Hier darf man nicht rauchen.','Burada sigara içilemez.'],
                ['Dürfen wir das Foto machen?','Fotoğraf çekebilir miyiz?'],
                ['Die Kinder dürfen heute länger aufbleiben.','Çocuklar bugün daha geç yatabilirler.'],
                ['Hier darf man nicht parken.','Buraya park edilemez.'],
                ['Darf ich Ihnen helfen?','Size yardım edebilir miyim?'],
                ['Du darfst meinen Computer benutzen.','Bilgisayarımı kullanabilirsin.'],
                ['Im Museum darf man nicht fotografieren.','Müzede fotoğraf çekilemez.'],
                ['Darf ich das Fenster öffnen?','Pencereyi açabilir miyim?'],
                ['Wir dürfen hier nicht laut sein.','Burada gürültü yapamayız.'],
                ['Kinder dürfen das nicht sehen.','Çocuklar bunu göremez.'],
                ['Darf er heute zu Hause bleiben?','O bugün evde kalabilir mi?'],
                ['Hier darf man nicht telefonieren.','Burada telefon konuşulamaz.'],
                ['Du darfst heute früher gehen.','Bugün daha erken gidebilirsin.'],
                ['In diesem Bereich darf man nicht essen.','Bu bölgede yemek yenilemez.'],
                ['Darf ich kurz stören?','Kısaca rahatsız edebilir miyim?'],
                ['Man darf hier kein Alkohol trinken.','Burada alkol içilemez.'],
                ['Dürft ihr das alleine entscheiden?','Bunu tek başınıza karar verebilir misiniz?'],
                ['In der Bibliothek darf man nicht sprechen.','Kütüphanede konuşulamaz.'],
                ['Darf ich Ihren Namen fragen?','Adınızı sorabilir miyim?'],
            ],
            'Können: Almanca Modal Fiiller' => [
                ['Ich kann gut schwimmen.','Ben iyi yüzebiliyorum.'],
                ['Kannst du Klavier spielen?','Piyano çalabilir misin?'],
                ['Er kann kein Deutsch sprechen.','O Almanca konuşamıyor.'],
                ['Wir können das Problem lösen.','Biz problemi çözebiliriz.'],
                ['Können Sie mir helfen, bitte?','Bana yardım edebilir misiniz, lütfen?'],
                ['Das kann ich nicht verstehen.','Bunu anlayamıyorum.'],
                ['Kann ich bitte Wasser haben?','Su alabilir miyim lütfen?'],
                ['Sie können sehr gut kochen.','O çok iyi yemek pişirebiliyor.'],
                ['Können wir morgen sprechen?','Yarın konuşabilir miyiz?'],
                ['Ich kann leider nicht kommen.','Maalesef gelemiyorum.'],
                ['Kannst du das bitte wiederholen?','Bunu lütfen tekrar eder misin?'],
                ['Er kann sehr schnell lesen.','O çok hızlı okuyabiliyor.'],
                ['Wir können hier warten.','Burada bekleyebiliriz.'],
                ['Kannst du mir bitte sagen, wo...?','Bana ... nerede olduğunu söyleyebilir misin?'],
                ['Ich kann das alleine machen.','Bunu tek başıma yapabilirim.'],
                ['Können Sie bitte langsamer sprechen?','Lütfen daha yavaş konuşabilir misiniz?'],
                ['Das Kind kann schon lesen.','Çocuk artık okuyabiliyor.'],
                ['Kannst du heute Abend kommen?','Bu akşam gelebilir misin?'],
                ['Ich kann gut Fahrrad fahren.','İyi bisiklet sürebiliyorum.'],
                ['Können wir das zusammen machen?','Bunu birlikte yapabilir miyiz?'],
            ],
            'Müssen: Almanca Modal Fiiller' => [
                ['Ich muss jeden Tag arbeiten.','Her gün çalışmam gerekiyor.'],
                ['Du musst jetzt schlafen gehen.','Şimdi uyumaya gitmen gerekiyor.'],
                ['Er muss pünktlich sein.','O dakik olmak zorunda.'],
                ['Wir müssen früh aufstehen.','Erken kalkmamız gerekiyor.'],
                ['Muss ich das wirklich machen?','Bunu gerçekten yapmak zorunda mıyım?'],
                ['Das Kind muss Hausaufgaben machen.','Çocuğun ödev yapması gerekiyor.'],
                ['Ich muss zum Arzt gehen.','Doktora gitmem gerekiyor.'],
                ['Müssen wir das bezahlen?','Bunu ödemek zorunda mıyız?'],
                ['Er muss jeden Tag Medikamente nehmen.','O her gün ilaç almak zorunda.'],
                ['Du musst mehr Wasser trinken.','Daha fazla su içmen gerekiyor.'],
                ['Ich muss leider absagen.','Maalesef iptal etmem gerekiyor.'],
                ['Wir müssen uns beeilen.','Acele etmemiz gerekiyor.'],
                ['Muss sie morgen arbeiten?','Onun yarın çalışması gerekiyor mu?'],
                ['Ich muss noch einkaufen.','Hâlâ alışveriş yapmam gerekiyor.'],
                ['Er muss die Prüfung bestehen.','O sınavı geçmek zorunda.'],
                ['Müssen Sie heute in die Stadt?','Bugün şehre gitmeniz gerekiyor mu?'],
                ['Das muss ein Fehler sein.','Bu bir hata olmalı.'],
                ['Ich muss jeden Tag üben.','Her gün pratik yapmam gerekiyor.'],
                ['Wir müssen das bis Freitag fertigmachen.','Bunu Cuma\'ya kadar bitirmemiz gerekiyor.'],
                ['Du musst dich entscheiden.','Karar vermen gerekiyor.'],
            ],
            'Sollen: Almanca Modal Fiiller' => [
                ['Ich soll dir etwas ausrichten.','Sana bir şey iletmem gerekiyor.'],
                ['Du sollst pünktlich sein!','Dakik olmalısın!'],
                ['Was soll ich jetzt machen?','Şimdi ne yapmalıyım?'],
                ['Er soll zum Chef kommen.','Şefe gelmesi gerekiyor.'],
                ['Wir sollen das Projekt beenden.','Projeyi bitirmemiz gerekiyor.'],
                ['Soll ich dir helfen?','Sana yardım etmemi ister misin?'],
                ['Die Kinder sollen leise sein.','Çocukların sessiz olması gerekiyor.'],
                ['Du sollst nicht lügen.','Yalan söylememelisin.'],
                ['Soll er anrufen?','O aramalı mı?'],
                ['Was sollen wir mitbringen?','Ne getirmeliyiz?'],
                ['Er soll laut Arzt mehr trinken.','Doktora göre daha fazla içmeli.'],
                ['Ich soll diese Formulare ausfüllen.','Bu formları doldurmam gerekiyor.'],
                ['Sollen wir auf euch warten?','Sizi beklememiz mi gerekiyor?'],
                ['Das soll nicht wieder passieren.','Bu bir daha olmamalı.'],
                ['Er soll sehr klug sein.','Onun çok zeki olduğu söyleniyor.'],
                ['Was soll das bedeuten?','Bu ne anlama geliyor?'],
                ['Ich soll morgen früh aufstehen.','Yarın erken kalkmam gerekiyor.'],
                ['Soll ich das Fenster schließen?','Pencereyi kapatmamı ister misiniz?'],
                ['Du sollst deine Medizin nehmen.','İlacını alman gerekiyor.'],
                ['Wir sollen pünktlich da sein.','Orada dakik olmamız gerekiyor.'],
            ],
            'Aile Üyeleri' => [
                ['Mein Vater ist 55 Jahre alt.','Babam 55 yaşında.'],
                ['Meine Mutter arbeitet als Ärztin.','Annem doktor olarak çalışıyor.'],
                ['Ich habe einen Bruder und eine Schwester.','Bir erkek ve bir kız kardeşim var.'],
                ['Meine Großmutter kocht sehr gut.','Büyükannem çok iyi yemek pişiriyor.'],
                ['Mein Großvater liest jeden Tag die Zeitung.','Büyükbabam her gün gazete okuyor.'],
                ['Wie heißt deine Schwester?','Kız kardeşinin adı ne?'],
                ['Mein Bruder wohnt in Berlin.','Erkek kardeşim Berlin\'de yaşıyor.'],
                ['Wir besuchen unsere Eltern am Wochenende.','Hafta sonu ebeveynlerimizi ziyaret ediyoruz.'],
                ['Mein Onkel kommt aus der Türkei.','Amcam Türkiye\'den geliyor.'],
                ['Meine Tante hat drei Kinder.','Teyzem üç çocuğu var.'],
                ['Hast du Geschwister?','Kardeşin var mı?'],
                ['Mein Cousin studiert Informatik.','Erkek kuzenimi bilgisayar bilimleri okuyor.'],
                ['Die Kinder spielen zusammen im Garten.','Çocuklar birlikte bahçede oynuyor.'],
                ['Mein Mann ist sehr nett.','Kocam çok nazik.'],
                ['Meine Frau arbeitet als Lehrerin.','Karım öğretmen olarak çalışıyor.'],
                ['Wie alt sind deine Kinder?','Çocukların kaç yaşında?'],
                ['Meine Eltern wohnen in München.','Ebeveynlerim Münih\'te yaşıyor.'],
                ['Wir essen zusammen als Familie.','Aile olarak birlikte yemek yiyoruz.'],
                ['Mein Sohn ist in der Schule.','Oğlum okulda.'],
                ['Meine Tochter ist sehr klug.','Kızım çok zeki.'],
            ],
            'Yiyecek ve İçecekler' => [
                ['Ich kaufe jeden Tag frisches Brot.','Her gün taze ekmek alıyorum.'],
                ['Was möchten Sie zum Frühstück?','Kahvaltıda ne istersiniz?'],
                ['Der Käse ist sehr lecker.','Peynir çok lezzetli.'],
                ['Ich trinke morgens immer Milch.','Sabahları her zaman süt içiyorum.'],
                ['Wir essen heute Abend Pizza.','Bu akşam pizza yiyoruz.'],
                ['Das Gemüse ist frisch und gesund.','Sebze taze ve sağlıklı.'],
                ['Er mag kein Fleisch.','O et sevmiyor.'],
                ['Die Kinder essen gern Obst.','Çocuklar meyve yemeyi seviyor.'],
                ['Ich hätte gern einen Apfelsaft.','Bir elma suyu istiyorum.'],
                ['Das Essen im Restaurant ist sehr gut.','Restoranda yemek çok iyi.'],
                ['Magst du Kaffee oder Tee?','Kahve mi çay mı seversin?'],
                ['Wir kochen heute Fisch.','Bugün balık pişiriyoruz.'],
                ['Ich habe Hunger. Essen wir!','Acıktım. Yiyelim!'],
                ['Das Brot ist noch warm.','Ekmek hâlâ sıcak.'],
                ['Trinkst du lieber Wasser oder Saft?','Su mu yoksa meyve suyu mu içersin?'],
                ['Ich esse mittags oft Reis.','Öğle vakti genelde pilav yerim.'],
                ['Die Bananen sind reif.','Muzlar olgun.'],
                ['Er kocht ein Ei zum Frühstück.','Kahvaltı için bir yumurta pişiriyor.'],
                ['Was isst du am liebsten?','En çok ne yemeyi seversin?'],
                ['Ich esse kein Fleisch, ich bin Vegetarier.','Et yemiyorum, vejetaryenim.'],
            ],
            'Vücudumuz ve Sağlık' => [
                ['Mein Kopf tut weh.','Başım ağrıyor.'],
                ['Ich habe Halsschmerzen.','Boğaz ağrım var.'],
                ['Mein Bauch tut weh.','Karnım ağrıyor.'],
                ['Ich habe Fieber.','Ateşim var.'],
                ['Mein Rücken schmerzt.','Sırtım ağrıyor.'],
                ['Er hat Kopfschmerzen.','Onun baş ağrısı var.'],
                ['Ich fühle mich nicht gut.','Kendimi iyi hissetmiyorum.'],
                ['Sie hat Schnupfen und Husten.','Onun nezle ve öksürüğü var.'],
                ['Ich muss zum Arzt gehen.','Doktora gitmem gerekiyor.'],
                ['Hast du Schmerzen?','Ağrın var mı?'],
                ['Meine Augen sind müde.','Gözlerim yorgun.'],
                ['Ich habe mir den Arm gebrochen.','Kolumu kırdım.'],
                ['Das Bein tut ihm weh.','Onun bacağı ağrıyor.'],
                ['Ich bin erkältet.','Üşüttüm/Nezle oldum.'],
                ['Der Arzt untersucht den Patienten.','Doktor hastayı muayene ediyor.'],
                ['Ich nehme jeden Tag Vitamine.','Her gün vitamin alıyorum.'],
                ['Mein Hals ist rot.','Boğazım kırmızı.'],
                ['Ich muss ins Krankenhaus.','Hastaneye gitmem gerekiyor.'],
                ['Meine Hand blutet.','Elim kanıyor.'],
                ['Ich brauche ein Rezept vom Arzt.','Doktordan bir reçeteye ihtiyacım var.'],
            ],
            'Ev ve Eşyalar' => [
                ['Meine Wohnung hat drei Zimmer.','Dairem üç odalı.'],
                ['Das Wohnzimmer ist groß und hell.','Oturma odası büyük ve aydınlık.'],
                ['In der Küche koche ich jeden Tag.','Mutfakta her gün yemek pişiriyorum.'],
                ['Das Bett ist sehr bequem.','Yatak çok rahat.'],
                ['Wir haben einen großen Tisch im Esszimmer.','Yemek odasında büyük bir masamız var.'],
                ['Das Bad ist klein, aber modern.','Banyo küçük ama modern.'],
                ['Das Sofa steht im Wohnzimmer.','Koltuk oturma odasında duruyor.'],
                ['Ich brauche einen neuen Schrank.','Yeni bir dolaba ihtiyacım var.'],
                ['Das Haus hat einen Garten.','Evin bir bahçesi var.'],
                ['Die Küche ist sehr praktisch.','Mutfak çok pratik.'],
                ['In meinem Schlafzimmer gibt es viele Bücher.','Yatak odamda çok kitap var.'],
                ['Der Stuhl ist kaputt.','Sandalye bozuk.'],
                ['Wir kaufen neue Möbel für das Wohnzimmer.','Oturma odası için yeni mobilya alıyoruz.'],
                ['Das Fenster lässt viel Licht herein.','Pencere çok ışık giriyor.'],
                ['Die Waschmaschine ist im Bad.','Çamaşır makinesi banyoda.'],
                ['Ich stelle die Lampe auf den Tisch.','Lambayı masanın üstüne koyuyorum.'],
                ['Das Zimmer ist aufgeräumt.','Oda toplu.'],
                ['Wir wohnen in der zweiten Etage.','İkinci katta yaşıyoruz.'],
                ['Die Tür zum Balkon ist offen.','Balkona giden kapı açık.'],
                ['Ich hänge das Bild an die Wand.','Resmi duvara asıyorum.'],
            ],
            'Kıyafetler' => [
                ['Ich trage heute ein blaues T-Shirt.','Bugün mavi bir tişört giyiyorum.'],
                ['Die Hose ist zu groß für mich.','Pantolon benim için çok büyük.'],
                ['Sie trägt ein schönes rotes Kleid.','O güzel kırmızı bir elbise giyiyor.'],
                ['Ich kaufe mir neue Schuhe.','Kendime yeni ayakkabı alıyorum.'],
                ['Der Mantel ist warm und bequem.','Palto sıcak ve rahat.'],
                ['Welche Jacke gefällt dir besser?','Hangi ceket sana daha çok yakışıyor?'],
                ['Ich suche eine Hose in Größe 36.','36 beden bir pantolon arıyorum.'],
                ['Er trägt immer einen Anzug zur Arbeit.','O her zaman işe takım elbise giyiyor.'],
                ['Darf ich das Kleid anprobieren?','Bu elbiseyi deneyebilir miyim?'],
                ['Die Schuhe drücken mich.','Ayakkabılar beni sıkıştırıyor.'],
                ['Ich ziehe meinen Pullover an, weil es kalt ist.','Hava soğuk olduğu için kazağımı giyiyorum.'],
                ['Die Socken sind aus Baumwolle.','Çoraplar pamuktan yapılmış.'],
                ['Er trägt gern bunte Hemden.','O renkli gömlekler giymeyi seviyor.'],
                ['Mein Rock ist zu kurz.','Eteğim çok kısa.'],
                ['Ich brauche eine warme Mütze für den Winter.','Kış için sıcak bir bere lazım.'],
                ['Die Handschuhe sind aus Leder.','Eldivenler deriden yapılmış.'],
                ['Was ziehst du heute an?','Bugün ne giyiyorsun?'],
                ['Er hat seinen Schal vergessen.','O atkısını unuttu.'],
                ['Meine Lieblingsjacke ist schwarz.','En sevdiğim ceket siyah.'],
                ['Die Kleidung ist sehr teuer hier.','Burada kıyafetler çok pahalı.'],
            ],
        ];

        foreach ($data as $lessonTitle => $sentences) {
            $lesson = Lesson::where('lesson_title', $lessonTitle)->first();
            if (!$lesson) { echo "SKIP: $lessonTitle\n"; continue; }

            $exercise = Exercise::firstOrCreate(
                ['lesson_id' => $lesson->id, 'title' => $lessonTitle . ' Alıştırmaları'],
                ['order_index' => 1, 'is_active' => true]
            );

            // Clear and re-add to ensure 20 sentences
            $exercise->items()->delete();
            foreach ($sentences as $idx => [$g, $t]) {
                ExerciseItem::create([
                    'exercise_id' => $exercise->id,
                    'german' => $g, 'turkish' => $t,
                    'order_index' => $idx + 1
                ]);
            }
            echo "OK: $lessonTitle (" . count($sentences) . " sentences)\n";
        }
    }
}
